import random

def guess_game():
        # correct answer randomly generated by random module
        correct_answer = random.randint(1,10)
        # try except block for invalid inputs
        try:
            user = int(input("Guess the right number (Numbers Only): "))

            if user == correct_answer:
                print("You are correct!")
                return True # setting to true will end while loop
            else:
                print("You are incorrect!")     
        # ensures to only type number
        except ValueError:
            print("Please input a valid number")


game_start = None

while not game_start: 
    game_start = guess_game()

    


